iwlibs.py: Argument split() must be bytes
File "/usr/lib/python3.9/site-packages/pythonwifi/iwlibs.py", line 96, in getWNICnames
  File "/usr/lib/python3.9/site-packages/pythonwifi/iwlibs.py", line 117, in getConfiguredWNICnames
TypeError: a bytes-like object is required, not 'str'